export namespace SampleData {

  const SpareTeam = {
    id: 0,
    name: "Spare List"
  };

  const Cliff27sTeam = {
    id: 1,
    name: "Cliff's 27's",
    gamesPlayed: 30,
    wins: 17,
    losses: 10,
    ties: 3,
    goalsFor: 170,
    goalsAgainst: 166,
    streak: { streakType: "L", streakCount: 1 },
    lastTen: [
      { awayTeam: "Sean & Gord's Gang",         awayScore: 2,	homeScore: 6,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Keith's Torys",              awayScore: 7,	homeScore: 5,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Cliff's 27's",               awayScore: 7,	homeScore: 7,	homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Cliff's 27's",               awayScore: 2,	homeScore: 3,	homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Cliff's 27's",               awayScore: 8,	homeScore: 5,	homeTeam: "Keith's Torys" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 4,	homeScore: 7,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 5,	homeScore: 8,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Keith's Torys",              awayScore: 5,	homeScore: 6,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Cliff's 27's",               awayScore: 1,	homeScore: 3,	homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Cliff's 27's",               awayScore: 3,	homeScore: 4,	homeTeam: "Sean & Gord's Gang" },
    ]
  };

  const KeithToryTeam = {
    id: 2,
    name: "Keith's Torys",
    gamesPlayed: 30,
    wins: 9,
    losses: 18,
    ties: 3,
    goalsFor: 151,
    goalsAgainst: 188,
    streak: { streakType: "W", streakCount: 1 },
    lastTen: [
      { awayTeam: "Keith's Torys",              awayScore: 4,	homeScore: 9,	homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Keith's Torys",              awayScore: 7,	homeScore: 5,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 8,	homeScore: 4,	homeTeam: "Keith's Torys" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 6,	homeScore: 9,	homeTeam: "Keith's Torys" },
      { awayTeam: "Cliff's 27's",               awayScore: 8,	homeScore: 5,	homeTeam: "Keith's Torys" },
      { awayTeam: "Keith's Torys",              awayScore: 4,	homeScore: 11,	homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Keith's Torys",              awayScore: 2,	homeScore: 7,	homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Keith's Torys",              awayScore: 5,	homeScore: 6,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 6,	homeScore: 3,	homeTeam: "Keith's Torys" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 4,	homeScore: 11,	homeTeam: "Keith's Torys" },
    ]
  };

  const LucLeedsGrenvillersTeam = {
    id: 3,
    name: "Luc's Leeds & Grenvillers",
    gamesPlayed: 30,
    wins: 11,
    losses: 17,
    ties: 2,
    goalsFor: 160,
    goalsAgainst: 173,
    streak: { streakType: "L", streakCount: 1 },
    lastTen: [
      { awayTeam: "Keith's Torys",               awayScore: 4,   homeScore: 5,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 8,   homeScore: 7,   homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Cliff's 27's",                awayScore: 7,   homeScore: 7,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 6,   homeScore: 9,   homeTeam: "Keith's Torys" },
      { awayTeam: "Sean & Gord's Gang",          awayScore: 5,   homeScore: 4,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 4,   homeScore: 7,   homeTeam: "Cliff's 27's" },
      { awayTeam: "Keith's Torys",               awayScore: 2,   homeScore: 7,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 1,   homeScore: 9,   homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Cliff's 27's",                awayScore: 1,   homeScore: 3,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 4,   homeScore: 11,  homeTeam: "Keith's Torys" },
    ]
  };

  const SeanGordGangTeam = {
    id: 4,
    name: "Sean & Gord's Gang",
    gamesPlayed: 30,
    wins: 18,
    losses: 10,
    ties: 2,
    goalsFor: 186,
    goalsAgainst: 140,
    streak: { streakType: "W", streakCount: 3 },
    lastTen: [
      { awayTeam: "Keith's Torys",              awayScore: 4, homeScore: 9, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 8, homeScore: 7, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 8, homeScore: 4, homeTeam: "Keith's Torys" },
      { awayTeam: "Cliff's 27's",               awayScore: 2, homeScore: 3, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 5, homeScore: 4, homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Keith's Torys",              awayScore: 4, homeScore: 11, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 5, homeScore: 8, homeTeam: "Cliff's 27's" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 1, homeScore: 9, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 6, homeScore: 3, homeTeam: "Keith's Torys" },
      { awayTeam: "Cliff's 27's",               awayScore: 3, homeScore: 4, homeTeam: "Sean & Gord's Gang" },
    ]
  };

  export const Players = JSON.stringify([
    { id: 0, name: "Russell Whitlock",        team: SeanGordGangTeam.name,         gamesPlayed: 32,  goals: 93,  assists: 39, points: 132, penalties: 2,  },
    { id: 1, name: "David Leung",             team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 30,  goals: 57,  assists: 36, points: 93,  penalties: 1,  },
    { id: 2, name: "Alex Beall",              team: Cliff27sTeam.name,             gamesPlayed: 33,  goals: 50,  assists: 29, points: 79,  penalties: 0,  },
    { id: 3, name: "Glenn Ashford",           team: KeithToryTeam.name,            gamesPlayed: 34,  goals: 28,  assists: 51, points: 79,  penalties: 3,  },
    { id: 4, name: "Daryl Ebata",             team: KeithToryTeam.name,            gamesPlayed: 29,  goals: 44,  assists: 21, points: 65,  penalties: 0,  },
    { id: 5, name: "Pete Rosano",             team: Cliff27sTeam.name,             gamesPlayed: 40,  goals: 29,  assists: 33, points: 62,  penalties: 0,  },
    { id: 6, name: "Glenn Lester",            team: Cliff27sTeam.name,             gamesPlayed: 34,  goals: 36,  assists: 24, points: 60,  penalties: 1,  },
    { id: 7, name: "Rob McGowan",             team: SeanGordGangTeam.name,         gamesPlayed: 33,  goals: 34,  assists: 26, points: 60,  penalties: 9,  },
    { id: 8, name: "Sean Charlebois",         team: SeanGordGangTeam.name,         gamesPlayed: 24,  goals: 11,  assists: 48, points: 59,  penalties: 1,  },
    { id: 9, name: "Phil Goodall",            team: SeanGordGangTeam.name,         gamesPlayed: 32,  goals: 7,   assists: 50, points: 57,  penalties: 14, },
    { id: 10, name: "Brian Clare",            team: Cliff27sTeam.name,             gamesPlayed: 24,  goals: 33,  assists: 22, points: 55,  penalties: 2,  },
    { id: 11, name: "Scott Tetreault",        team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 27,  goals: 20,  assists: 34, points: 54,  penalties: 6,  },
    { id: 12, name: "Tim Rollwagen",          team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 33,  goals: 3,   assists: 51, points: 54,  penalties: 1,  },
    { id: 13, name: "Martin Van Schyndel",    team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 32,  goals: 10,  assists: 42, points: 52,  penalties: 1,  },
    { id: 14, name: "Adam Melong",            team: KeithToryTeam.name,            gamesPlayed: 35,  goals: 9,   assists: 42, points: 51,  penalties: 9,  },
    { id: 15, name: "Rodd Lamarche",          team: KeithToryTeam.name,            gamesPlayed: 31,  goals: 20,  assists: 28, points: 48,  penalties: 1,  },
    { id: 16, name: "Pete Robinson",          team: SeanGordGangTeam.name,         gamesPlayed: 29,  goals: 12,  assists: 36, points: 48,  penalties: 0,  },
    { id: 17, name: "Sean Sinclair",          team: KeithToryTeam.name,            gamesPlayed: 32,  goals: 10,  assists: 38, points: 48,  penalties: 0,  },
    { id: 18, name: "Mark Cepella",           team: Cliff27sTeam.name,             gamesPlayed: 29,  goals: 8,   assists: 39, points: 47,  penalties: 14, },
    { id: 19, name: "Joe Shapiro",            team: Cliff27sTeam.name,             gamesPlayed: 27,  goals: 24,  assists: 19, points: 43,  penalties: 1,  },
    { id: 20, name: "Brent Jackson",          team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 30,  goals: 21,  assists: 21, points: 42,  penalties: 1,  },
    { id: 21, name: "Les Banks",              team: Cliff27sTeam.name,             gamesPlayed: 37,  goals: 7,   assists: 35, points: 42,  penalties: 2,  },
    { id: 22, name: "Louis Lamothe",          team: KeithToryTeam.name,            gamesPlayed: 34,  goals: 10,  assists: 31, points: 41,  penalties: 0,  },
    { id: 23, name: "Doug Gordon",            team: SeanGordGangTeam.name,         gamesPlayed: 22,  goals: 10,  assists: 29, points: 39,  penalties: 0,  },
    { id: 24, name: "Graeme Gordon",          team: SeanGordGangTeam.name,         gamesPlayed: 33,  goals: 5,   assists: 34, points: 39,  penalties: 2,  },
    { id: 25, name: "Luc Brunet",             team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 27,  goals: 7,   assists: 26, points: 33,  penalties: 1,  },
    { id: 26, name: "Ryan Graham",            team: SeanGordGangTeam.name,         gamesPlayed: 30,  goals: 13,  assists: 13, points: 26,  penalties: 1,  },
    { id: 27, name: "Andrew Harold",          team: SeanGordGangTeam.name,         gamesPlayed: 34,  goals: 4,   assists: 16, points: 20,  penalties: 0,  },
    { id: 28, name: "Jamie Leclair",          team: SeanGordGangTeam.name,         gamesPlayed: 18,  goals: 7,   assists: 12, points: 19,  penalties: 2,  },
    { id: 29, name: "Chris Pearson",          team: KeithToryTeam.name,            gamesPlayed: 12,  goals: 3,   assists: 16, points: 19,  penalties: 0,  },
    { id: 30, name: "Martin Keyes",           team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 15,  goals: 8,   assists: 10, points: 18,  penalties: 0,  },
    { id: 31, name: "Jeff de Jong",           team: KeithToryTeam.name,            gamesPlayed: 11,  goals: 10,  assists: 7,  points: 17,  penalties: 0,  },
    { id: 32, name: "Steve Palisek",          team: Cliff27sTeam.name,             gamesPlayed: 15,  goals: 0,   assists: 15, points: 15,  penalties: 2,  },
    { id: 33, name: "Adam Turnbull",          team: Cliff27sTeam.name,             gamesPlayed: 29,  goals: 9,   assists: 5,  points: 14,  penalties: 3,  },
    { id: 34, name: "Phillip Pratt-Vaugeois", team: Cliff27sTeam.name,             gamesPlayed: 7,   goals: 3,   assists: 10, points: 13,  penalties: 4,  },
    { id: 35, name: "Gerry Ebata",            team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 26,  goals: 5,   assists: 6,  points: 11,  penalties: 2,  },
    { id: 36, name: "Keith MacEwen",          team: KeithToryTeam.name,            gamesPlayed: 21,  goals: 2,   assists: 9,  points: 11,  penalties: 0,  },
    { id: 37, name: "Faud Khan",              team: KeithToryTeam.name,            gamesPlayed: 19,  goals: 1,   assists: 10, points: 11,  penalties: 0,  },
    { id: 38, name: "Nick Coyne",             team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 5,   goals: 4,   assists: 6,  points: 10,  penalties: 1,  },
    { id: 39, name: "Eric Fabien",            team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 10,  goals: 4,   assists: 5,  points: 9,   penalties: 3,  },
    { id: 40, name: "Andrew Giffin",          team: KeithToryTeam.name,            gamesPlayed: 12,  goals: 5,   assists: 2,  points: 7,   penalties: 0,  },
    { id: 41, name: "Daniel Dole",            team: Cliff27sTeam.name,             gamesPlayed: 25,  goals: 1,   assists: 6,  points: 7,   penalties: 4,  },
    { id: 42, name: "Scott Parker",	          team: SpareTeam.name,                gamesPlayed: 5,   goals: 2,   assists: 4,  points: 6,   penalties: 0,  },
    { id: 43, name: "Mike Ostrom",	          team: SpareTeam.name,                gamesPlayed: 12,  goals: 0,   assists: 6,  points: 6,   penalties: 0,  },
    { id: 44, name: "Cliff Lapenskie",        team: Cliff27sTeam.name,             gamesPlayed: 33,  goals: 1,   assists: 4,  points: 5,   penalties: 0,  },
    { id: 45, name: "Matt Bourgon",	          team: SpareTeam.name,                gamesPlayed: 3,   goals: 0,   assists: 4,  points: 4,   penalties: 0,  },
    { id: 46, name: "Mike Ziebarth",	      team: SpareTeam.name,                gamesPlayed: 4,   goals: 0,   assists: 4,  points: 4,   penalties: 0,  },
    { id: 47, name: "Kaven Roussel",	      team: SpareTeam.name,                gamesPlayed: 8,   goals: 1,   assists: 2,  points: 3,   penalties: 0,  },
    { id: 48, name: "Brad Little",	          team: SpareTeam.name,                gamesPlayed: 3,   goals: 0,   assists: 3,  points: 3,   penalties: 0,  },
    { id: 49, name: "Pj Marie",	              team: SpareTeam.name,                gamesPlayed: 19,  goals: 0,   assists: 3,  points: 3,   penalties: 0,  },
    { id: 50, name: "Drea Brunet",            team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 25,  goals: 0,   assists: 3,  points: 3,   penalties: 0,  },
    { id: 51, name: "Dave Matheson",          team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 5,   goals: 2,   assists: 0,  points: 2,   penalties: 0,  },
    { id: 52, name: "Taj Smith",	          team: SpareTeam.name,                gamesPlayed: 2,   goals: 1,   assists: 1,  points: 2,   penalties: 0,  },
    { id: 53, name: "Melissa Van Schyndel",	  team: SpareTeam.name,                gamesPlayed: 3,   goals: 0,   assists: 2,  points: 2,   penalties: 0,  },
    { id: 54, name: "Gordon Cockell",	      team: SpareTeam.name,                gamesPlayed: 1,   goals: 0,   assists: 1,  points: 1,   penalties: 0,  },
    { id: 55, name: "Jeff Brisson",	          team: SpareTeam.name,                gamesPlayed: 1,   goals: 0,   assists: 1,  points: 1,   penalties: 0,  },
    { id: 56, name: "Keith Gagnon",	          team: SpareTeam.name,                gamesPlayed: 1,   goals: 0,   assists: 1,  points: 1,   penalties: 0,  },
    { id: 57, name: "Kyle McGuire",	          team: SpareTeam.name,                gamesPlayed: 1,   goals: 0,   assists: 1,  points: 1,   penalties: 0,  },
    { id: 58, name: "Gerry Myers",	          team: SpareTeam.name,                gamesPlayed: 2,   goals: 0,   assists: 1,  points: 1,   penalties: 0,  },
    { id: 59, name: "Erik McLaughlin",	      team: SpareTeam.name,                gamesPlayed: 4,   goals: 0,   assists: 1,  points: 1,   penalties: 0,  },
    { id: 60, name: "Jonas Strindlund",       team: KeithToryTeam.name,            gamesPlayed: 7,   goals: 0,   assists: 1,  points: 1,   penalties: 1,  },
    { id: 61, name: "Rob Beland",             team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 12,  goals: 0,   assists: 1,  points: 1,   penalties: 0,  },
    { id: 62, name: "Francois Burton",        team: LucLeedsGrenvillersTeam.name,  gamesPlayed: 16,  goals: 0,   assists: 1,  points: 1,   penalties: 0,  },
    { id: 63, name: "Gordon Brown",	          team: SpareTeam.name,                gamesPlayed: 0,   goals: 0,   assists: 0,  points: 0,   penalties: 0,  },
    { id: 64, name: "Paul Gillis",	          team: SpareTeam.name,                gamesPlayed: 1,   goals: 0,   assists: 0,  points: 0,   penalties: 0,  },
    { id: 65, name: "Rob O'Neil",	          team: SpareTeam.name,                gamesPlayed: 1,   goals: 0,   assists: 0,  points: 0,   penalties: 0,  },
    { id: 66, name: "Robert Rodger",	      team: SpareTeam.name,                gamesPlayed: 1,   goals: 0,   assists: 0,  points: 0,   penalties: 0,  },
    { id: 67, name: "Antonio Mazzotta",       team: KeithToryTeam.name,            gamesPlayed: 16,  goals: 0,   assists: 0,  points: 0,   penalties: 0,  },
    { id: 68, name: "Matthew Michaluk",       team: SeanGordGangTeam.name,         gamesPlayed: 17,  goals: 0,   assists: 0,  points: 0,   penalties: 0,  },
  ]);

  export const Teams = JSON.stringify([
    SpareTeam,
    Cliff27sTeam,
    KeithToryTeam,
    LucLeedsGrenvillersTeam,
    SeanGordGangTeam,

    //{
    //  id: 0,
    //  name: "Spare List"
    //},
    //{
    //  id: 1,
    //  name: "Cliff's 27's",
    //  gamesPlayed: 30,
    //  wins: 17,
    //  losses: 10,
    //  ties: 3,
    //  goalsFor: 170,
    //  goalsAgainst: 166,
    //  streak: { streakType: "L", streakCount: 1 },
    //  lastTen: [
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 2,	homeScore: 6,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Keith's Torys",              awayScore: 7,	homeScore: 5,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 7,	homeScore: 7,	homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 2,	homeScore: 3,	homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 8,	homeScore: 5,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 4,	homeScore: 7,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 5,	homeScore: 8,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Keith's Torys",              awayScore: 5,	homeScore: 6,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 1,	homeScore: 3,	homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 3,	homeScore: 4,	homeTeam: "Sean & Gord's Gang" },
    //  ]
    //},
    //{
    //  id: 2,
    //  name: "Keith's Torys",
    //  gamesPlayed: 30,
    //  wins: 9,
    //  losses: 18,
    //  ties: 3,
    //  goalsFor: 151,
    //  goalsAgainst: 188,
    //  streak: { streakType: "W", streakCount: 1 },
    //  lastTen: [
    //    { awayTeam: "Keith's Torys",              awayScore: 4,	homeScore: 9,	homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Keith's Torys",              awayScore: 7,	homeScore: 5,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 8,	homeScore: 4,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 6,	homeScore: 9,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 8,	homeScore: 5,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Keith's Torys",              awayScore: 4,	homeScore: 11,	homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Keith's Torys",              awayScore: 2,	homeScore: 7,	homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Keith's Torys",              awayScore: 5,	homeScore: 6,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 6,	homeScore: 3,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 4,	homeScore: 11,	homeTeam: "Keith's Torys" },
    //  ]
    //},
    //{
    //  id: 3,
    //  name: "Luc's Leeds & Grenvillers",
    //  gamesPlayed: 30,
    //  wins: 11,
    //  losses: 17,
    //  ties: 2,
    //  goalsFor: 160,
    //  goalsAgainst: 173,
    //  streak: { streakType: "L", streakCount: 1 },
    //  lastTen: [
    //    { awayTeam: "Keith's Torys",               awayScore: 4,   homeScore: 5,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 8,   homeScore: 7,   homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Cliff's 27's",                awayScore: 7,   homeScore: 7,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 6,   homeScore: 9,   homeTeam: "Keith's Torys" },
    //    { awayTeam: "Sean & Gord's Gang",          awayScore: 5,   homeScore: 4,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 4,   homeScore: 7,   homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Keith's Torys",               awayScore: 2,   homeScore: 7,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 1,   homeScore: 9,   homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Cliff's 27's",                awayScore: 1,   homeScore: 3,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 4,   homeScore: 11,  homeTeam: "Keith's Torys" },
    //  ]
    //},
    //{
    //  id: 4,
    //  name: "Sean & Gord's Gang",
    //  gamesPlayed: 30,
    //  wins: 18,
    //  losses: 10,
    //  ties: 2,
    //  goalsFor: 186,
    //  goalsAgainst: 140,
    //  streak: { streakType: "W", streakCount: 3 },
    //  lastTen: [
    //    { awayTeam: "Keith's Torys",              awayScore: 4, homeScore: 9, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 8, homeScore: 7, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 8, homeScore: 4, homeTeam: "Keith's Torys" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 2, homeScore: 3, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 5, homeScore: 4, homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Keith's Torys",              awayScore: 4, homeScore: 11, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 5, homeScore: 8, homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 1, homeScore: 9, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 6, homeScore: 3, homeTeam: "Keith's Torys" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 3, homeScore: 4, homeTeam: "Sean & Gord's Gang" },
    //  ]
    //},
  ]);

  export const Games = JSON.stringify([
    { id: 0,  date: "May 2, 2018 07:00",  gameType: "League",   awayTeam: SeanGordGangTeam.name,         awayScore: 7,	homeScore: 6,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 1,  date: "May 4, 2018 07:00",  gameType: "League",   awayTeam: Cliff27sTeam.name,             awayScore: 4,	homeScore: 9,	homeTeam: KeithToryTeam.name,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 2,  date: "May 7, 2018 07:00",  gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 7,	homeScore: 9,	homeTeam: Cliff27sTeam.name,	            arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 3,  date: "May 9, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam.name,            awayScore: 7,	homeScore: 7,	homeTeam: SeanGordGangTeam.name,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 4,  date: "May 11, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,         awayScore: 8,	homeScore: 10,	homeTeam: Cliff27sTeam.name,	            arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 5,  date: "May 14, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,            awayScore: 1,	homeScore: 2,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 6,  date: "May 16, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 0,	homeScore: 7,	homeTeam: SeanGordGangTeam.name,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 7,  date: "May 18, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 3,	homeScore: 6,	homeTeam: Cliff27sTeam.name,	            arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 8,  date: "May 22, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	            awayScore: 7,	homeScore: 4,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Walter Baker (Rink A)" },
    { id: 9,  date: "May 23, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,         awayScore: 5,	homeScore: 6,	homeTeam: KeithToryTeam.name,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 10,  date: "May 25, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 6,	homeScore: 3,	homeTeam: KeithToryTeam.name,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 11,  date: "May 28, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 0,	homeScore: 4,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 12,  date: "May 29, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 4,	homeScore: 4,	homeTeam: KeithToryTeam.name,	        arena: "Walter Baker (Rink A)" },
    { id: 13,  date: "May 30, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 5,	homeScore: 5,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 14,  date: "Jun 1, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 10,	homeScore: 6,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 15,  date: "Jun 4, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 4,	homeScore: 8,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 16,  date: "Jun 5, 2018 07:00",  gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 6,	homeScore: 7,	homeTeam: Cliff27sTeam.name,	            arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 17,  date: "Jun 6, 2018 07:00",  gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 7,	homeScore: 6,	homeTeam: Cliff27sTeam.name,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 18,  date: "Jun 8, 2018 07:00",  gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 4,	homeScore: 7,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 19,  date: "Jun 11, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 3,	homeScore: 7,	homeTeam: Cliff27sTeam.name,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 20,  date: "Jun 12, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 5,	homeScore: 2,	homeTeam: KeithToryTeam.name,	        arena: "Walter Baker (Rink A)" },
    { id: 21,  date: "Jun 13, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 6,	homeScore: 5,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 22,  date: "Jun 15, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 8,	homeScore: 2,	homeTeam: KeithToryTeam.name,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 23,  date: "Jun 18, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 4,	homeScore: 7,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 24,  date: "Jun 19, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 7,	homeScore: 4,	homeTeam: KeithToryTeam.name,	        arena: "Walter Baker (Rink A)" },
    { id: 25,  date: "Jun 20, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 2,	homeScore: 9,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 26,  date: "Jun 22, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 4,	homeScore: 5,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 27,  date: "Jun 25, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 5,	homeScore: 4,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 28,  date: "Jun 26, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 5,	homeScore: 6,	homeTeam: Cliff27sTeam.name,	            arena: "Walter Baker (Rink A)" },
    { id: 29,  date: "Jun 27, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 4,	homeScore: 9,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 30,  date: "Jun 29, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 12,	homeScore: 2,	homeTeam: Cliff27sTeam.name,	            arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 31,  date: "Jul 3, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 6,	homeScore: 6,	homeTeam: Cliff27sTeam.name,	            arena: "Walter Baker (Rink A)" },
    { id: 32,  date: "Jul 4, 2018 07:00",  gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 5,	homeScore: 6,	homeTeam: KeithToryTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 33,  date: "Jul 6, 2018 07:00",  gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 6,	homeScore: 5,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 34,  date: "Jul 9, 2018 07:00",  gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 6,	homeScore: 3,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 35,  date: "Jul 10, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 5,	homeScore: 6,	homeTeam: KeithToryTeam.name,	        arena: "Walter Baker (Rink A)" },
    { id: 36,  date: "Jul 11, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 2,	homeScore: 11,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 37,  date: "Jul 13, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 9,	homeScore: 8,	homeTeam: KeithToryTeam.name,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 38,  date: "Jul 16, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 9,	homeScore: 7,	homeTeam: Cliff27sTeam.name,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 39,  date: "Jul 17, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 4,	homeScore: 5,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Walter Baker (Rink A)" },
    { id: 40,  date: "Jul 18, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 2,	homeScore: 6,	homeTeam: Cliff27sTeam.name,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 41,  date: "Jul 20, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 4,	homeScore: 9,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 42,  date: "Jul 23, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 8,	homeScore: 7,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 43,  date: "Jul 24, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 7,	homeScore: 5,	homeTeam: Cliff27sTeam.name,	            arena: "Walter Baker (Rink A)" },
    { id: 44,  date: "Jul 25, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 8,	homeScore: 4,	homeTeam: KeithToryTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 45,  date: "Jul 27, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 7,	homeScore: 7,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 46,  date: "Jul 30, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 2,	homeScore: 3,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 47,  date: "Jul 31, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 6,	homeScore: 9,	homeTeam: KeithToryTeam.name,	        arena: "Walter Baker (Rink A)" },
    { id: 48,  date: "Aug 1, 2018 07:00",  gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 5,	homeScore: 4,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 49,  date: "Aug 2, 2018 07:00",  gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 8,	homeScore: 5,	homeTeam: KeithToryTeam.name,	        arena: "Walter Baker (Rink A)" },
    { id: 50,  date: "Aug 7, 2018 07:00",  gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 4,	homeScore: 7,	homeTeam: Cliff27sTeam.name,	            arena: "Walter Baker (Rink A)" },
    { id: 51,  date: "Aug 8, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 4,	homeScore: 11,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 52,  date: "Aug 9, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 2,	homeScore: 7,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Walter Baker (Rink A)" },
    { id: 53,  date: "Aug 13, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 5,	homeScore: 8,	homeTeam: Cliff27sTeam.name,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 54,  date: "Aug 14, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam.name,	        awayScore: 5,	homeScore: 6,	homeTeam: Cliff27sTeam.name,	            arena: "Walter Baker (Rink A)" },
    { id: 55,  date: "Aug 15, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name, awayScore: 1,	homeScore: 9,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 56,  date: "Aug 16, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 1,	homeScore: 3,	homeTeam: LucLeedsGrenvillersTeam.name,	arena: "Walter Baker (Rink A)" },
    { id: 57,  date: "Aug 20, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam.name,	    awayScore: 6,	homeScore: 3,	homeTeam: KeithToryTeam.name,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 58,  date: "Aug 21, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam.name, awayScore: 4,	homeScore: 11,	homeTeam: KeithToryTeam.name,	        arena: "Walter Baker (Rink A)" },
    { id: 59,  date: "Aug 22, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam.name,	        awayScore: 3,	homeScore: 4,	homeTeam: SeanGordGangTeam.name,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 60,  date: "Aug 23, 2018 07:00", gameType: "Playoff",  awayTeam: KeithToryTeam.name,	        awayScore: 2,	homeScore: 5,	homeTeam: SeanGordGangTeam.name,	        arena: "Walter Baker (Rink A)" },
    { id: 61,  date: "Aug 27, 2018 07:00", gameType: "Playoff",  awayTeam: LucLeedsGrenvillersTeam.name,	awayScore: 2,	homeScore: 7,	homeTeam: Cliff27sTeam.name,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena)" },
    { id: 62,  date: "Aug 30, 2018 07:00", gameType: "Playoff",  awayTeam: Cliff27sTeam.name,	        awayScore: 3,	homeScore: 7,	homeTeam: SeanGordGangTeam.name,	        arena: "Walter Baker (Rink A)" }
  ]);

}
