export namespace SampleData {

  const SpareTeam = {
    id: 0,
    name: "Spare List"
  };

  const Cliff27sTeam = {
    id: 1,
    name: "Cliff's 27's",
    gamesPlayed: 30,
    wins: 17,
    losses: 10,
    ties: 3,
    goalsFor: 170,
    goalsAgainst: 166,
    streak: { streakType: "L", streakCount: 1 },
    lastTen: [
      { awayTeam: "Sean & Gord's Gang",         awayScore: 2,	homeScore: 6,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Keith's Torys",              awayScore: 7,	homeScore: 5,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Cliff's 27's",               awayScore: 7,	homeScore: 7,	homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Cliff's 27's",               awayScore: 2,	homeScore: 3,	homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Cliff's 27's",               awayScore: 8,	homeScore: 5,	homeTeam: "Keith's Torys" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 4,	homeScore: 7,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 5,	homeScore: 8,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Keith's Torys",              awayScore: 5,	homeScore: 6,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Cliff's 27's",               awayScore: 1,	homeScore: 3,	homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Cliff's 27's",               awayScore: 3,	homeScore: 4,	homeTeam: "Sean & Gord's Gang" },
    ]
  };

  const KeithToryTeam = {
    id: 2,
    name: "Keith's Torys",
    gamesPlayed: 30,
    wins: 9,
    losses: 18,
    ties: 3,
    goalsFor: 151,
    goalsAgainst: 188,
    streak: { streakType: "W", streakCount: 1 },
    lastTen: [
      { awayTeam: "Keith's Torys",              awayScore: 4,	homeScore: 9,	homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Keith's Torys",              awayScore: 7,	homeScore: 5,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 8,	homeScore: 4,	homeTeam: "Keith's Torys" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 6,	homeScore: 9,	homeTeam: "Keith's Torys" },
      { awayTeam: "Cliff's 27's",               awayScore: 8,	homeScore: 5,	homeTeam: "Keith's Torys" },
      { awayTeam: "Keith's Torys",              awayScore: 4,	homeScore: 11,	homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Keith's Torys",              awayScore: 2,	homeScore: 7,	homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Keith's Torys",              awayScore: 5,	homeScore: 6,	homeTeam: "Cliff's 27's" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 6,	homeScore: 3,	homeTeam: "Keith's Torys" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 4,	homeScore: 11,	homeTeam: "Keith's Torys" },
    ]
  };

  const LucLeedsGrenvillersTeam = {
    id: 3,
    name: "Luc's Leeds & Grenvillers",
    gamesPlayed: 30,
    wins: 11,
    losses: 17,
    ties: 2,
    goalsFor: 160,
    goalsAgainst: 173,
    streak: { streakType: "L", streakCount: 1 },
    lastTen: [
      { awayTeam: "Keith's Torys",               awayScore: 4,   homeScore: 5,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 8,   homeScore: 7,   homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Cliff's 27's",                awayScore: 7,   homeScore: 7,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 6,   homeScore: 9,   homeTeam: "Keith's Torys" },
      { awayTeam: "Sean & Gord's Gang",          awayScore: 5,   homeScore: 4,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 4,   homeScore: 7,   homeTeam: "Cliff's 27's" },
      { awayTeam: "Keith's Torys",               awayScore: 2,   homeScore: 7,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 1,   homeScore: 9,   homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Cliff's 27's",                awayScore: 1,   homeScore: 3,   homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 4,   homeScore: 11,  homeTeam: "Keith's Torys" },
    ]
  };

  const SeanGordGangTeam = {
    id: 4,
    name: "Sean & Gord's Gang",
    gamesPlayed: 30,
    wins: 18,
    losses: 10,
    ties: 2,
    goalsFor: 186,
    goalsAgainst: 140,
    streak: { streakType: "W", streakCount: 3 },
    lastTen: [
      { awayTeam: "Keith's Torys",              awayScore: 4, homeScore: 9, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 8, homeScore: 7, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 8, homeScore: 4, homeTeam: "Keith's Torys" },
      { awayTeam: "Cliff's 27's",               awayScore: 2, homeScore: 3, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 5, homeScore: 4, homeTeam: "Luc's Leeds & Grenvillers" },
      { awayTeam: "Keith's Torys",              awayScore: 4, homeScore: 11, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 5, homeScore: 8, homeTeam: "Cliff's 27's" },
      { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 1, homeScore: 9, homeTeam: "Sean & Gord's Gang" },
      { awayTeam: "Sean & Gord's Gang",         awayScore: 6, homeScore: 3, homeTeam: "Keith's Torys" },
      { awayTeam: "Cliff's 27's",               awayScore: 3, homeScore: 4, homeTeam: "Sean & Gord's Gang" },
    ]
  };

  export const Players = JSON.stringify([
    { id: 0, name: "Russell Whitlock",        team: SeanGordGangTeam,         gamesPlayedSeason: 32,  goalsSeason: 93,  assistsSeason: 39, pointsSeason: 132, penaltiesSeason: 2, active: true },
    { id: 1, name: "David Leung",             team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 30,  goalsSeason: 57,  assistsSeason: 36, pointsSeason: 93,  penaltiesSeason: 1, active: true },
    { id: 2, name: "Alex Beall",              team: Cliff27sTeam,             gamesPlayedSeason: 33,  goalsSeason: 50,  assistsSeason: 29, pointsSeason: 79,  penaltiesSeason: 0, active: true },
    { id: 3, name: "Glenn Ashford",           team: KeithToryTeam,            gamesPlayedSeason: 34,  goalsSeason: 28,  assistsSeason: 51, pointsSeason: 79,  penaltiesSeason: 3, active: true },
    { id: 4, name: "Daryl Ebata",             team: KeithToryTeam,            gamesPlayedSeason: 29,  goalsSeason: 44,  assistsSeason: 21, pointsSeason: 65,  penaltiesSeason: 0, active: true },
    { id: 5, name: "Pete Rosano",             team: Cliff27sTeam,             gamesPlayedSeason: 40,  goalsSeason: 29,  assistsSeason: 33, pointsSeason: 62,  penaltiesSeason: 0, active: true },
    { id: 6, name: "Glenn Lester",            team: Cliff27sTeam,             gamesPlayedSeason: 34,  goalsSeason: 36,  assistsSeason: 24, pointsSeason: 60,  penaltiesSeason: 1, active: true },
    { id: 7, name: "Rob McGowan",             team: SeanGordGangTeam,         gamesPlayedSeason: 33,  goalsSeason: 34,  assistsSeason: 26, pointsSeason: 60,  penaltiesSeason: 9, active: true },
    { id: 8, name: "Sean Charlebois",         team: SeanGordGangTeam,         gamesPlayedSeason: 24,  goalsSeason: 11,  assistsSeason: 48, pointsSeason: 59,  penaltiesSeason: 1, active: true },
    { id: 9, name: "Phil Goodall",            team: SeanGordGangTeam,         gamesPlayedSeason: 32,  goalsSeason: 7,   assistsSeason: 50, pointsSeason: 57,  penaltiesSeason: 14, active: true },
    { id: 10, name: "Brian Clare",            team: Cliff27sTeam,             gamesPlayedSeason: 24,  goalsSeason: 33,  assistsSeason: 22, pointsSeason: 55,  penaltiesSeason: 2, active: true },
    { id: 11, name: "Scott Tetreault",        team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 27,  goalsSeason: 20,  assistsSeason: 34, pointsSeason: 54,  penaltiesSeason: 6, active: true },
    { id: 12, name: "Tim Rollwagen",          team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 33,  goalsSeason: 3,   assistsSeason: 51, pointsSeason: 54,  penaltiesSeason: 1, active: true },
    { id: 13, name: "Martin Van Schyndel",    team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 32,  goalsSeason: 10,  assistsSeason: 42, pointsSeason: 52,  penaltiesSeason: 1, active: true },
    { id: 14, name: "Adam Melong",            team: KeithToryTeam,            gamesPlayedSeason: 35,  goalsSeason: 9,   assistsSeason: 42, pointsSeason: 51,  penaltiesSeason: 9, active: true },
    { id: 15, name: "Rodd Lamarche",          team: KeithToryTeam,            gamesPlayedSeason: 31,  goalsSeason: 20,  assistsSeason: 28, pointsSeason: 48,  penaltiesSeason: 1, active: true },
    { id: 16, name: "Pete Robinson",          team: SeanGordGangTeam,         gamesPlayedSeason: 29,  goalsSeason: 12,  assistsSeason: 36, pointsSeason: 48,  penaltiesSeason: 0, active: true },
    { id: 17, name: "Sean Sinclair",          team: KeithToryTeam,            gamesPlayedSeason: 32,  goalsSeason: 10,  assistsSeason: 38, pointsSeason: 48,  penaltiesSeason: 0, active: true },
    { id: 18, name: "Mark Cepella",           team: Cliff27sTeam,             gamesPlayedSeason: 29,  goalsSeason: 8,   assistsSeason: 39, pointsSeason: 47,  penaltiesSeason: 14, active: true },
    { id: 19, name: "Joe Shapiro",            team: Cliff27sTeam,             gamesPlayedSeason: 27,  goalsSeason: 24,  assistsSeason: 19, pointsSeason: 43,  penaltiesSeason: 1, active: true },
    { id: 20, name: "Brent Jackson",          team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 30,  goalsSeason: 21,  assistsSeason: 21, pointsSeason: 42,  penaltiesSeason: 1, active: true },
    { id: 21, name: "Les Banks",              team: Cliff27sTeam,             gamesPlayedSeason: 37,  goalsSeason: 7,   assistsSeason: 35, pointsSeason: 42,  penaltiesSeason: 2, active: true },
    { id: 22, name: "Louis Lamothe",          team: KeithToryTeam,            gamesPlayedSeason: 34,  goalsSeason: 10,  assistsSeason: 31, pointsSeason: 41,  penaltiesSeason: 0, active: true },
    { id: 23, name: "Doug Gordon",            team: SeanGordGangTeam,         gamesPlayedSeason: 22,  goalsSeason: 10,  assistsSeason: 29, pointsSeason: 39,  penaltiesSeason: 0, active: true },
    { id: 24, name: "Graeme Gordon",          team: SeanGordGangTeam,         gamesPlayedSeason: 33,  goalsSeason: 5,   assistsSeason: 34, pointsSeason: 39,  penaltiesSeason: 2, active: true },
    { id: 25, name: "Luc Brunet",             team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 27,  goalsSeason: 7,   assistsSeason: 26, pointsSeason: 33,  penaltiesSeason: 1, active: true },
    { id: 26, name: "Ryan Graham",            team: SeanGordGangTeam,         gamesPlayedSeason: 30,  goalsSeason: 13,  assistsSeason: 13, pointsSeason: 26,  penaltiesSeason: 1, active: true },
    { id: 27, name: "Andrew Harold",          team: SeanGordGangTeam,         gamesPlayedSeason: 34,  goalsSeason: 4,   assistsSeason: 16, pointsSeason: 20,  penaltiesSeason: 0, active: true },
    { id: 28, name: "Jamie Leclair",          team: SeanGordGangTeam,         gamesPlayedSeason: 18,  goalsSeason: 7,   assistsSeason: 12, pointsSeason: 19,  penaltiesSeason: 2, active: true },
    { id: 29, name: "Chris Pearson",          team: KeithToryTeam,            gamesPlayedSeason: 12,  goalsSeason: 3,   assistsSeason: 16, pointsSeason: 19,  penaltiesSeason: 0, active: true },
    { id: 30, name: "Martin Keyes",           team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 15,  goalsSeason: 8,   assistsSeason: 10, pointsSeason: 18,  penaltiesSeason: 0, active: true },
    { id: 31, name: "Jeff de Jong",           team: KeithToryTeam,            gamesPlayedSeason: 11,  goalsSeason: 10,  assistsSeason: 7,  pointsSeason: 17,  penaltiesSeason: 0, active: true },
    { id: 32, name: "Steve Palisek",          team: Cliff27sTeam,             gamesPlayedSeason: 15,  goalsSeason: 0,   assistsSeason: 15, pointsSeason: 15,  penaltiesSeason: 2, active: true },
    { id: 33, name: "Adam Turnbull",          team: Cliff27sTeam,             gamesPlayedSeason: 29,  goalsSeason: 9,   assistsSeason: 5,  pointsSeason: 14,  penaltiesSeason: 3, active: true },
    { id: 34, name: "Phillip Pratt-Vaugeois", team: Cliff27sTeam,             gamesPlayedSeason: 7,   goalsSeason: 3,   assistsSeason: 10, pointsSeason: 13,  penaltiesSeason: 4, active: true },
    { id: 35, name: "Gerry Ebata",            team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 26,  goalsSeason: 5,   assistsSeason: 6,  pointsSeason: 11,  penaltiesSeason: 2, active: true },
    { id: 36, name: "Keith MacEwen",          team: KeithToryTeam,            gamesPlayedSeason: 21,  goalsSeason: 2,   assistsSeason: 9,  pointsSeason: 11,  penaltiesSeason: 0, active: true },
    { id: 37, name: "Faud Khan",              team: KeithToryTeam,            gamesPlayedSeason: 19,  goalsSeason: 1,   assistsSeason: 10, pointsSeason: 11,  penaltiesSeason: 0, active: true },
    { id: 38, name: "Nick Coyne",             team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 5,   goalsSeason: 4,   assistsSeason: 6,  pointsSeason: 10,  penaltiesSeason: 1, active: true },
    { id: 39, name: "Eric Fabien",            team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 10,  goalsSeason: 4,   assistsSeason: 5,  pointsSeason: 9,   penaltiesSeason: 3, active: true },
    { id: 40, name: "Andrew Giffin",          team: KeithToryTeam,            gamesPlayedSeason: 12,  goalsSeason: 5,   assistsSeason: 2,  pointsSeason: 7,   penaltiesSeason: 0, active: true },
    { id: 41, name: "Daniel Dole",            team: Cliff27sTeam,             gamesPlayedSeason: 25,  goalsSeason: 1,   assistsSeason: 6,  pointsSeason: 7,   penaltiesSeason: 4, active: true },
    { id: 42, name: "Scott Parker",	          team: SpareTeam,                gamesPlayedSeason: 5,   goalsSeason: 2,   assistsSeason: 4,  pointsSeason: 6,   penaltiesSeason: 0, active: true },
    { id: 43, name: "Mike Ostrom",	          team: SpareTeam,                gamesPlayedSeason: 12,  goalsSeason: 0,   assistsSeason: 6,  pointsSeason: 6,   penaltiesSeason: 0, active: true },
    { id: 44, name: "Cliff Lapenskie",        team: Cliff27sTeam,             gamesPlayedSeason: 33,  goalsSeason: 1,   assistsSeason: 4,  pointsSeason: 5,   penaltiesSeason: 0, active: true },
    { id: 45, name: "Matt Bourgon",	          team: SpareTeam,                gamesPlayedSeason: 3,   goalsSeason: 0,   assistsSeason: 4,  pointsSeason: 4,   penaltiesSeason: 0, active: true },
    { id: 46, name: "Mike Ziebarth",	      team: SpareTeam,                gamesPlayedSeason: 4,   goalsSeason: 0,   assistsSeason: 4,  pointsSeason: 4,   penaltiesSeason: 0, active: true },
    { id: 47, name: "Kaven Roussel",	      team: SpareTeam,                gamesPlayedSeason: 8,   goalsSeason: 1,   assistsSeason: 2,  pointsSeason: 3,   penaltiesSeason: 0, active: true },
    { id: 48, name: "Brad Little",	          team: SpareTeam,                gamesPlayedSeason: 3,   goalsSeason: 0,   assistsSeason: 3,  pointsSeason: 3,   penaltiesSeason: 0, active: true },
    { id: 49, name: "Pj Marie",	              team: SpareTeam,                gamesPlayedSeason: 19,  goalsSeason: 0,   assistsSeason: 3,  pointsSeason: 3,   penaltiesSeason: 0, active: true },
    { id: 50, name: "Drea Brunet",            team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 25,  goalsSeason: 0,   assistsSeason: 3,  pointsSeason: 3,   penaltiesSeason: 0, active: true },
    { id: 51, name: "Dave Matheson",          team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 5,   goalsSeason: 2,   assistsSeason: 0,  pointsSeason: 2,   penaltiesSeason: 0, active: true },
    { id: 52, name: "Taj Smith",	          team: SpareTeam,                gamesPlayedSeason: 2,   goalsSeason: 1,   assistsSeason: 1,  pointsSeason: 2,   penaltiesSeason: 0, active: true },
    { id: 53, name: "Melissa Van Schyndel",	  team: SpareTeam,                gamesPlayedSeason: 3,   goalsSeason: 0,   assistsSeason: 2,  pointsSeason: 2,   penaltiesSeason: 0, active: true },
    { id: 54, name: "Gordon Cockell",	      team: SpareTeam,                gamesPlayedSeason: 1,   goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 0, active: true },
    { id: 55, name: "Jeff Brisson",	          team: SpareTeam,                gamesPlayedSeason: 1,   goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 0, active: true },
    { id: 56, name: "Keith Gagnon",	          team: SpareTeam,                gamesPlayedSeason: 1,   goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 0, active: true },
    { id: 57, name: "Kyle McGuire",	          team: SpareTeam,                gamesPlayedSeason: 1,   goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 0, active: true },
    { id: 58, name: "Gerry Myers",	          team: SpareTeam,                gamesPlayedSeason: 2,   goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 0, active: true },
    { id: 59, name: "Erik McLaughlin",	      team: SpareTeam,                gamesPlayedSeason: 4,   goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 0, active: true },
    { id: 60, name: "Jonas Strindlund",       team: KeithToryTeam,            gamesPlayedSeason: 7,   goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 1, active: true },
    { id: 61, name: "Rob Beland",             team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 12,  goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 0, active: true },
    { id: 62, name: "Francois Burton",        team: LucLeedsGrenvillersTeam,  gamesPlayedSeason: 16,  goalsSeason: 0,   assistsSeason: 1,  pointsSeason: 1,   penaltiesSeason: 0, active: true },
    { id: 63, name: "Gordon Brown",	          team: SpareTeam,                gamesPlayedSeason: 0,   goalsSeason: 0,   assistsSeason: 0,  pointsSeason: 0,   penaltiesSeason: 0, active: true },
    { id: 64, name: "Paul Gillis",	          team: SpareTeam,                gamesPlayedSeason: 1,   goalsSeason: 0,   assistsSeason: 0,  pointsSeason: 0,   penaltiesSeason: 0, active: true },
    { id: 65, name: "Rob O'Neil",	          team: SpareTeam,                gamesPlayedSeason: 1,   goalsSeason: 0,   assistsSeason: 0,  pointsSeason: 0,   penaltiesSeason: 0, active: true },
    { id: 66, name: "Robert Rodger",	      team: SpareTeam,                gamesPlayedSeason: 1,   goalsSeason: 0,   assistsSeason: 0,  pointsSeason: 0,   penaltiesSeason: 0, active: true },
    { id: 67, name: "Antonio Mazzotta",       team: KeithToryTeam,            gamesPlayedSeason: 16,  goalsSeason: 0,   assistsSeason: 0,  pointsSeason: 0,   penaltiesSeason: 0, active: true },
    { id: 68, name: "Matthew Michaluk",       team: SeanGordGangTeam,         gamesPlayedSeason: 17,  goalsSeason: 0,   assistsSeason: 0,  pointsSeason: 0,   penaltiesSeason: 0, active: true },
  ]);

  export const Teams = JSON.stringify([
    SpareTeam,
    Cliff27sTeam,
    KeithToryTeam,
    LucLeedsGrenvillersTeam,
    SeanGordGangTeam,

    //{
    //  id: 0,
    //  name: "Spare List"
    //},
    //{
    //  id: 1,
    //  name: "Cliff's 27's",
    //  gamesPlayed: 30,
    //  wins: 17,
    //  losses: 10,
    //  ties: 3,
    //  goalsFor: 170,
    //  goalsAgainst: 166,
    //  streak: { streakType: "L", streakCount: 1 },
    //  lastTen: [
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 2,	homeScore: 6,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Keith's Torys",              awayScore: 7,	homeScore: 5,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 7,	homeScore: 7,	homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 2,	homeScore: 3,	homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 8,	homeScore: 5,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 4,	homeScore: 7,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 5,	homeScore: 8,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Keith's Torys",              awayScore: 5,	homeScore: 6,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 1,	homeScore: 3,	homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 3,	homeScore: 4,	homeTeam: "Sean & Gord's Gang" },
    //  ]
    //},
    //{
    //  id: 2,
    //  name: "Keith's Torys",
    //  gamesPlayed: 30,
    //  wins: 9,
    //  losses: 18,
    //  ties: 3,
    //  goalsFor: 151,
    //  goalsAgainst: 188,
    //  streak: { streakType: "W", streakCount: 1 },
    //  lastTen: [
    //    { awayTeam: "Keith's Torys",              awayScore: 4,	homeScore: 9,	homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Keith's Torys",              awayScore: 7,	homeScore: 5,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 8,	homeScore: 4,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 6,	homeScore: 9,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 8,	homeScore: 5,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Keith's Torys",              awayScore: 4,	homeScore: 11,	homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Keith's Torys",              awayScore: 2,	homeScore: 7,	homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Keith's Torys",              awayScore: 5,	homeScore: 6,	homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 6,	homeScore: 3,	homeTeam: "Keith's Torys" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 4,	homeScore: 11,	homeTeam: "Keith's Torys" },
    //  ]
    //},
    //{
    //  id: 3,
    //  name: "Luc's Leeds & Grenvillers",
    //  gamesPlayed: 30,
    //  wins: 11,
    //  losses: 17,
    //  ties: 2,
    //  goalsFor: 160,
    //  goalsAgainst: 173,
    //  streak: { streakType: "L", streakCount: 1 },
    //  lastTen: [
    //    { awayTeam: "Keith's Torys",               awayScore: 4,   homeScore: 5,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 8,   homeScore: 7,   homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Cliff's 27's",                awayScore: 7,   homeScore: 7,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 6,   homeScore: 9,   homeTeam: "Keith's Torys" },
    //    { awayTeam: "Sean & Gord's Gang",          awayScore: 5,   homeScore: 4,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 4,   homeScore: 7,   homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Keith's Torys",               awayScore: 2,   homeScore: 7,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 1,   homeScore: 9,   homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Cliff's 27's",                awayScore: 1,   homeScore: 3,   homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",   awayScore: 4,   homeScore: 11,  homeTeam: "Keith's Torys" },
    //  ]
    //},
    //{
    //  id: 4,
    //  name: "Sean & Gord's Gang",
    //  gamesPlayed: 30,
    //  wins: 18,
    //  losses: 10,
    //  ties: 2,
    //  goalsFor: 186,
    //  goalsAgainst: 140,
    //  streak: { streakType: "W", streakCount: 3 },
    //  lastTen: [
    //    { awayTeam: "Keith's Torys",              awayScore: 4, homeScore: 9, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 8, homeScore: 7, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 8, homeScore: 4, homeTeam: "Keith's Torys" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 2, homeScore: 3, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 5, homeScore: 4, homeTeam: "Luc's Leeds & Grenvillers" },
    //    { awayTeam: "Keith's Torys",              awayScore: 4, homeScore: 11, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 5, homeScore: 8, homeTeam: "Cliff's 27's" },
    //    { awayTeam: "Luc's Leeds & Grenvillers",  awayScore: 1, homeScore: 9, homeTeam: "Sean & Gord's Gang" },
    //    { awayTeam: "Sean & Gord's Gang",         awayScore: 6, homeScore: 3, homeTeam: "Keith's Torys" },
    //    { awayTeam: "Cliff's 27's",               awayScore: 3, homeScore: 4, homeTeam: "Sean & Gord's Gang" },
    //  ]
    //},
  ]);

  export const Games = JSON.stringify([
    { id: 0,  date: "May 2, 2018 07:00",  gameType: "League",   awayTeam: SeanGordGangTeam,         awayScore: 7,	homeScore: 6,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 1,  date: "May 4, 2018 07:00",  gameType: "League",   awayTeam: Cliff27sTeam,             awayScore: 4,	homeScore: 9,	homeTeam: KeithToryTeam,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 2,  date: "May 7, 2018 07:00",  gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 7,	homeScore: 9,	homeTeam: Cliff27sTeam,	            arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 3,  date: "May 9, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam,            awayScore: 7,	homeScore: 7,	homeTeam: SeanGordGangTeam,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 4,  date: "May 11, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,         awayScore: 8,	homeScore: 10,	homeTeam: Cliff27sTeam,	            arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 5,  date: "May 14, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,            awayScore: 1,	homeScore: 2,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 6,  date: "May 16, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 0,	homeScore: 7,	homeTeam: SeanGordGangTeam,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 7,  date: "May 18, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 3,	homeScore: 6,	homeTeam: Cliff27sTeam,	            arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 8,  date: "May 22, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	            awayScore: 7,	homeScore: 4,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Walter Baker (Rink A)" },
    { id: 9,  date: "May 23, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,         awayScore: 5,	homeScore: 6,	homeTeam: KeithToryTeam,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 10,  date: "May 25, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 6,	homeScore: 3,	homeTeam: KeithToryTeam,	        arena: "Minto Recreation Complex - Barrhaven - North" },
    { id: 11,  date: "May 28, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 0,	homeScore: 4,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 12,  date: "May 29, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 4,	homeScore: 4,	homeTeam: KeithToryTeam,	        arena: "Walter Baker (Rink A)" },
    { id: 13,  date: "May 30, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 5,	homeScore: 5,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 14,  date: "Jun 1, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 10,	homeScore: 6,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 15,  date: "Jun 4, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 4,	homeScore: 8,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 16,  date: "Jun 5, 2018 07:00",  gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 6,	homeScore: 7,	homeTeam: Cliff27sTeam,	            arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 17,  date: "Jun 6, 2018 07:00",  gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 7,	homeScore: 6,	homeTeam: Cliff27sTeam,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 18,  date: "Jun 8, 2018 07:00",  gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 4,	homeScore: 7,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 19,  date: "Jun 11, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 3,	homeScore: 7,	homeTeam: Cliff27sTeam,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 20,  date: "Jun 12, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 5,	homeScore: 2,	homeTeam: KeithToryTeam,	        arena: "Walter Baker (Rink A)" },
    { id: 21,  date: "Jun 13, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 6,	homeScore: 5,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 22,  date: "Jun 15, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 8,	homeScore: 2,	homeTeam: KeithToryTeam,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 23,  date: "Jun 18, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 4,	homeScore: 7,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 24,  date: "Jun 19, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 7,	homeScore: 4,	homeTeam: KeithToryTeam,	        arena: "Walter Baker (Rink A)" },
    { id: 25,  date: "Jun 20, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 2,	homeScore: 9,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 26,  date: "Jun 22, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 4,	homeScore: 5,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 27,  date: "Jun 25, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 5,	homeScore: 4,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 28,  date: "Jun 26, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 5,	homeScore: 6,	homeTeam: Cliff27sTeam,	            arena: "Walter Baker (Rink A)" },
    { id: 29,  date: "Jun 27, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 4,	homeScore: 9,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 30,  date: "Jun 29, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 12,	homeScore: 2,	homeTeam: Cliff27sTeam,	            arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 31,  date: "Jul 3, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 6,	homeScore: 6,	homeTeam: Cliff27sTeam,	            arena: "Walter Baker (Rink A)" },
    { id: 32,  date: "Jul 4, 2018 07:00",  gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 5,	homeScore: 6,	homeTeam: KeithToryTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 33,  date: "Jul 6, 2018 07:00",  gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 6,	homeScore: 5,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 34,  date: "Jul 9, 2018 07:00",  gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 6,	homeScore: 3,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 35,  date: "Jul 10, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 5,	homeScore: 6,	homeTeam: KeithToryTeam,	        arena: "Walter Baker (Rink A)" },
    { id: 36,  date: "Jul 11, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 2,	homeScore: 11,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 37,  date: "Jul 13, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 9,	homeScore: 8,	homeTeam: KeithToryTeam,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 38,  date: "Jul 16, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 9,	homeScore: 7,	homeTeam: Cliff27sTeam,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 39,  date: "Jul 17, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 4,	homeScore: 5,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Walter Baker (Rink A)" },
    { id: 40,  date: "Jul 18, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 2,	homeScore: 6,	homeTeam: Cliff27sTeam,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 41,  date: "Jul 20, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 4,	homeScore: 9,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 42,  date: "Jul 23, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 8,	homeScore: 7,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 43,  date: "Jul 24, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 7,	homeScore: 5,	homeTeam: Cliff27sTeam,	            arena: "Walter Baker (Rink A)" },
    { id: 44,  date: "Jul 25, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 8,	homeScore: 4,	homeTeam: KeithToryTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 45,  date: "Jul 27, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 7,	homeScore: 7,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 46,  date: "Jul 30, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 2,	homeScore: 3,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 47,  date: "Jul 31, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 6,	homeScore: 9,	homeTeam: KeithToryTeam,	        arena: "Walter Baker (Rink A)" },
    { id: 48,  date: "Aug 1, 2018 07:00",  gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 5,	homeScore: 4,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 49,  date: "Aug 2, 2018 07:00",  gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 8,	homeScore: 5,	homeTeam: KeithToryTeam,	        arena: "Walter Baker (Rink A)" },
    { id: 50,  date: "Aug 7, 2018 07:00",  gameType: "League",   awayTeam: LucLeedsGrenvillersTeam,	awayScore: 4,	homeScore: 7,	homeTeam: Cliff27sTeam,	            arena: "Walter Baker (Rink A)" },
    { id: 51,  date: "Aug 8, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 4,	homeScore: 11,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 52,  date: "Aug 9, 2018 07:00",  gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 2,	homeScore: 7,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Walter Baker (Rink A)" },
    { id: 53,  date: "Aug 13, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 5,	homeScore: 8,	homeTeam: Cliff27sTeam,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 54,  date: "Aug 14, 2018 07:00", gameType: "League",   awayTeam: KeithToryTeam,	        awayScore: 5,	homeScore: 6,	homeTeam: Cliff27sTeam,	            arena: "Walter Baker (Rink A)" },
    { id: 55,  date: "Aug 15, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam, awayScore: 1,	homeScore: 9,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 56,  date: "Aug 16, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 1,	homeScore: 3,	homeTeam: LucLeedsGrenvillersTeam,	arena: "Walter Baker (Rink A)" },
    { id: 57,  date: "Aug 20, 2018 07:00", gameType: "League",   awayTeam: SeanGordGangTeam,	    awayScore: 6,	homeScore: 3,	homeTeam: KeithToryTeam,	        arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena" },
    { id: 58,  date: "Aug 21, 2018 07:00", gameType: "League",   awayTeam: LucLeedsGrenvillersTeam, awayScore: 4,	homeScore: 11,	homeTeam: KeithToryTeam,	        arena: "Walter Baker (Rink A)" },
    { id: 59,  date: "Aug 22, 2018 07:00", gameType: "League",   awayTeam: Cliff27sTeam,	        awayScore: 3,	homeScore: 4,	homeTeam: SeanGordGangTeam,	        arena: "Nepean Sportsplex - Arena 2 (At the back)" },
    { id: 60,  date: "Aug 23, 2018 07:00", gameType: "Playoff",  awayTeam: KeithToryTeam,	        awayScore: 2,	homeScore: 5,	homeTeam: SeanGordGangTeam,	        arena: "Walter Baker (Rink A)" },
    { id: 61,  date: "Aug 27, 2018 07:00", gameType: "Playoff",  awayTeam: LucLeedsGrenvillersTeam,	awayScore: 2,	homeScore: 7,	homeTeam: Cliff27sTeam,	            arena: "Nepean Sportsplex - Arena 3 (Figure Skating Arena)" },
    { id: 62,  date: "Aug 30, 2018 07:00", gameType: "Playoff",  awayTeam: Cliff27sTeam,	        awayScore: 3,	homeScore: 7,	homeTeam: SeanGordGangTeam,	        arena: "Walter Baker (Rink A)" }
  ]);

}
